version: '3.8'
services:
  jira-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/jira
      - POSTGRES_USERNAME
      - POSTGRES_PASS
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=jira
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    ports:
      - 5432:5432
